override dependency specification to support Linux aarch64
The version of GCC
(https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi)
specified by nordicnrf52 is not available for Linux aarch64.
Eventually this override should be removed in favor of upstream updating
https://github.com/platformio/platform-nordicnrf52/blob/c70522d769c664fb03b760368016fc31988ab43e/platform.json#L37-L45

diff --git a/devices/RAKwireless/Dockerfile-rak4631 b/devices/RAKwireless/Dockerfile-rak4631
--- a/devices/RAKwireless/Dockerfile-rak4631
+++ b/devices/RAKwireless/Dockerfile-rak4631
@@ -10,19 +10,43 @@ FROM rerobots/hs-generic-platformio:latest
 
 RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unzip
 
+COPY platformio-rak4631.ini /root/platformio.ini
+
+# run command will fail, but this will fetch and install dependencies
 RUN cd /root/ \
-    && bash -c "source .platformio/penv/bin/activate \
-    && platformio pkg install -g --platform nordicnrf52 \
-    && platformio pkg install -g --library arduino \
-    && platformio pkg install -g --tool framework-arduinoadafruitnrf52 \
-    && platformio pkg install -g --tool framework-cmsis \
-    && platformio pkg install -g --tool tool-adafruit-nrfutil \
-    && platformio pkg install -g --tool tool-scons"
+    && mkdir src \
+    && echo "#include <Arduino.h>" > src/main.cpp \
+    && echo "#include <SPI.h>" >> src/main.cpp \
+    && echo "void setup() {}" >> src/main.cpp \
+    && echo "void loop() {}" >> src/main.cpp \
+    && bash -c "source $HOME/.platformio/penv/bin/activate \
+    && platformio run \
+    || true"
 
 RUN cd /root/ \
     && wget https://github.com/RAKWireless/WisBlock/raw/8d851fba7693f9339db0f857a92cd816163c5f7a/PlatformIO/RAK_PATCH.zip -O RAK_PATCH.zip \
     && mkdir .platformio/RAK_PATCH && cd .platformio/RAK_PATCH && unzip ../../RAK_PATCH.zip \
-    && python ./rak_patch.py
+    && bash -c "source $HOME/.platformio/penv/bin/activate \
+    && python ./rak_patch.py"
 # sha256sum d18cec33bc3fa297583fd3d9f6852c10c1b6cea4a361b9a6ea567f7cfcdbe9a3  RAK_PATCH.zip
+
+# run command will fail, but this will fetch and install remaining dependencies
+RUN cd /root/ \
+    && bash -c "source $HOME/.platformio/penv/bin/activate \
+    && platformio run \
+    || true"
+
+RUN cd /root/.platformio/RAK_PATCH \
+    && bash -c "source $HOME/.platformio/penv/bin/activate \
+    && python ./rak_patch.py"
+
+# The final run command must succeed
+RUN cd /root/ \
+    && bash -c "source $HOME/.platformio/penv/bin/activate \
+    && platformio run"
+
+# Clean up
+RUN cd /root/ \
+    && rm -rf src platformio.ini
 
 CMD ["/sbin/rerobots-hs-init.sh"]
